name: Run Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Configura o repositório
    - name: Check out code
      uses: actions/checkout@v3

    # Configura o ambiente Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    # Instala dependências
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flask
        pip install pytest

    # Executa os testes
    - name: Run tests
      run: |
        python -m unittest discover -s . -p "test_*.py"
